name: Haskell CI

on: [push]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.8.2'
        cabal-version: 'latest'
        
    - name: Configure the build
      run: |
        cabal configure --enable-tests --enable-benchmarks --disable-documentation
        cabal build all --dry-run

    - name: Install dependencies
      run: cabal build all --only-dependencies

    - name: Build
      run: cabal build all
      
    - name: Run tests
      run: cabal test
